apiVersion: v1

kind: ConfigMap

metadata:
  name: kafka-configmap

data:
  KAFKA_NODE_ID: "1" 
  CLUSTER_ID: ZWU1Y2JiNDctNDg3ZC
  KAFKA_PROCESS_ROLES: controller, broker
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0.kafka-service.default.svc.cluster.local:9091
  KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0.kafka-service.default.svc.cluster.local:9090
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
  